apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cd-pipeline-run-
spec:
  pipelineRef:
    name: cd-pipeline
  workspaces:
    - name: pipeline-workspace
      persistentVolumeClaim:
        claimName: pipelinerun-pvc
  params:
    - name: repo-url
      value: https://github.com/YOUR-USERNAME/YOUR-REPOSITORY.git
    - name: branch
      value: main
